### ISSUE TITLE
Название класса

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#1]
https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Model/WeatherDate.swift#L12

Не первый раз у тебя замечаю, сначала думал опечатки, но видимо просто ошибка: Data, а не Date — это два разных слова 👌

**Comment by EvangelinaKlyukay** [comment]
теперь точно запомню, срасибо)
