### ISSUE TITLE
Баг ;P

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#10]
![Simulator Screen Shot - iPhone 8 - 2020-09-04 at 01 54 04](https://user-images.githubusercontent.com/2250376/92181283-8fc47500-ee51-11ea-83a6-6db050ec3c34.png)
![Simulator Screen Shot - iPhone 8 - 2020-09-04 at 01 54 08](https://user-images.githubusercontent.com/2250376/92181284-90f5a200-ee51-11ea-8614-d77d87aaa404.png)
Если после запуска приложения кликнуть в поле ввода и сразу после этого Enter, то текст меняется — так и должно быть? Или плейсхолдер всегда должен быть одинаковым? ;)

**Comment by EvangelinaKlyukay** [comment]
Так задумано  
func textFieldShouldEndEditing(_ textField: UITextField) -> Bool {
        if textField.text != "" {
            return true
        } else {
            textField.placeholder = "Type something"
            return false
        }
    }

**Comment by h4pp** [comment]
А, то есть текст и должен быть разным? 'Search' и 'Type something'?

Если так, то это фича, а не баг и можешь закрыть issue 🖖
