### ISSUE TITLE
Реализация протоколов

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#11]
https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Controller/WeatherViewController.swift#L41

Вот это довольно важная с точки зрения структуры кода ошибка. Если ты делаешь экстеншон отдельно под конкретную цель, в твоем случае `UITextFieldDelegate` то внутри этого экстеншона должны быть только методы работы с реализуемым протоколом. 

Если хочешь вынести куда-то `@IBActions` чтобы красиво было — выдели им отдельный `extension WeatherViewController { ... }` и пусть они там будут — это хорошо и удобно

**Comment by EvangelinaKlyukay** [comment]
сделала

**Comment by h4pp** [comment]
Не стесняйся применять аналогичную практику на всех файлах, иногда удобно вынести приватные методы сущности куда-то в отдельный экстеншон, чтобы снова не мешать ими перед глазами 👌
