### ISSUE TITLE
Чет падазрительна -_-

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#12]
https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Controller/WeatherViewController.swift#L20

А почему он `var`? Потому что если сделать `let`, то будет ругаться при установке `.delegate` ?

Вообще всякие сервисные штуки не должны быть `var`, то есть изменяемые. Вот сделаешь замыкания вместо делегирования и эта проблема автопочинится :) А вообще если прям важно чтобы внутри менеджера/сервиса происходили изменения — сделай его классом, а не структурой

И обрати внимание в этом файле на области видимости методов и переменных

**Comment by EvangelinaKlyukay** [comment]
сделала
