### ISSUE TITLE
Сохранение последнего показанного города

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#13]
Добавь возможность сохранять последний известный город в `UserDefaults` чтобы это выглядело так: я зашел в приложение и нашел там Тамбов. Вышел из приложения, выгрузил его и зашел через некоторое время снова и хочу чтобы там сразу находился именно Тамбов, так как я последним смотрел именно его.

Точно также с геолокацией: сначала загрузишь все равно тот город который был в прошлой сессии, а потом придут координаты и ты загрузишь данные по актуальной локации

**Comment by EvangelinaKlyukay** [comment]
сделала
