### ISSUE TITLE
Область видимости + вынос "секретной" части

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#2]
https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Model/WeatherManager.swift#L20

Давай потихоньку начинать следить за так называемой областью видимости переменных и методов (`private`, `internal`, `public`). Старайся помечать словом `private` все переменные и методы, которые нужны только внутри класса/структуры и не торчат наружу. Как URL с адресом сервера, он же за пределами `WeatherManager` не используется?

И сразу раздели эту строку на 2, вынеси `appid` отдельной константой. Чаще всего такие штуки приходят откуда-то из файлов конфигураций и это должно входить в привычку 👌

**Comment by h4pp** [comment]
https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Model/WeatherManager.swift#L57

Вот здесь тоже и метод реквеста тоже наружу не торчит — ему тоже пригодится 👍

**Comment by h4pp** [comment]
> https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Model/WeatherManager.swift#L57
> 
> Вот здесь тоже и метод реквеста тоже наружу не торчит — ему тоже пригодится 👍

А вот этот метод? Он остался `internal`, а используется только внутри `WeatherManager` :]

**Comment by h4pp** [comment]
И еще чуть-чуть про область видимости, просто это правда полезно осознавать :)

```swift
extension WeatherViewController: WeatherManagerDelegate {
    internal func didUpdateWeather(_ weatherManager: WeatherManager, weather: WeatherModel) {
```

1) у тебя проект состоящий только из твоего проекта и ничего более, ты не разрабатываешь библиотеки и тд, пока что 😏 По этому использование модификатора видимости `internal` — избыточно, это базовый модификатор и лишний раз его писать — только нагружать глаза и пальцы :) 
2) исходя из того что библиотек ты пока не делаешь, то и модификатор `public` тоже не нужен, даже более чем `internal` на данном этапе
3) Если вдруг, так оказалось, что весь `extension` у тебя имеет одну область видимости для всех методов, то аккуратнее будет написать, например `private extension WeatherViewController: ...` указав модификатор прямо при объявлении расширения своего — это тоже окей и будет работать так как ожидается :) 

О чем я говорю когда начинаю про библиотеки: смотри, когда ты делаешь библиотечку, которая решает какую-то задачу и хочешь отдать ее другим разработчикам чтобы они ее использовали, то ты будешь должна определить методы доступные пользователям библиотеки с модификатором `public`, только такие поля и методы будут им видны. Всю свою логику работы между классами/структурами тебе необходимо будет держать в рамках `internal`, а штуки которые нужны только в рамках одного класса/структуры необходимо будет пометить `private`

Получается что ты даешь библиотеку пользователю и он видит в ней только 3 метода, на самом деле там под капотом 100 методов `internal` о существовании которых пользователь и не задумается никогда, а чтобы код не превращался в кашу ты прячешь от себя самого всякие мелочи за модификаторами `private` и о таких мелочах знаю только те классы/структуры в которых они определены :) 

Так что пробегись по всем файлам, внимательно глянь где кто используется и расставь только `private` для тех, кто не "торчит на ружу"

**Comment by EvangelinaKlyukay** [comment]
Сделала
