### ISSUE TITLE
URL вместо строки

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#4]
https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Model/WeatherManager.swift#L34

Давай заменим `urlString` на настоящий URL и все параметры будем добавлять туда используя URLComponents

Почитай про URLComponents, тогда у тебя и "секретная" часть урла будет добавляться с помощью `queryItems` как и все остальные параметры. Довольно часто встречаются задачи "расковырять урл" вынимая какие-то конкретные параметры или перебирая все подряд и тогда URLComponents прям помогает

Пора вырастать из склеивания строк :) Это ты уже освоила ;)

**Comment by EvangelinaKlyukay** [comment]
сделала
