### ISSUE TITLE
Создание одного URLSession

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#5]
https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Model/WeatherManager.swift#L38

заведи просто где-то сверху приватную константу `URLSession(configuration: .default) ` и обращайся к ней, это достаточно тяжелая операция чтобы перед каждым реквестом создавать сессию. Причем если бы параметры сессии были какие-то уникальные, то надо было бы что-то придумывать, а в твоем случае достаточно одной константы 👌

**Comment by EvangelinaKlyukay** [comment]
сделала
