### ISSUE TITLE
По верстке небольшой вопрос:

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#6]
а это в уроках где-то говорилось про верстку полностью через `UIStackView`? Или это ты поэкспериментировала с лэйаутом и так набросала этот экран?
Так то сверстано аккуратно, но надо иметь всегда в голове, что в AutoLayout нынешний очень туго справляется со сложными экранами на стаках. На таком большом статичном это незаметно, а вот если у тебя будет таблица где много маленьких ячеек внутри которых много стаков — это прям заметно туго будет скроллиться

Я к тому что пробуй и экспериментируй, конечно, это классно, но не забывай про такой нюанс 👌 Там где это удобно и возможно — лучше использовать автолэйаут, и чем он будет проще — тем производительнее

**Comment by EvangelinaKlyukay** [comment]
ну с это мы уже обсудили)
