### ISSUE TITLE
Отдельный менеджер про локацию

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#7]
https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Controller/WeatherViewController.swift#L21

Попробуй вынести весь код связаный с геолокацией в отдельный `LocationManager`, пусть у него будут использоваться только те методы которые тебе нужны — это хорошая практика. Сейчас у тебя в контроллер импортируется весь фреймворк CoreLocation — пусть это будет где-то в другом файле. Во-первых: контроллеру и так забот хватает чтобы еще вот такие низкоуровневые штуки выполнять, а во-вторых: вдруг фреймворк по определению геолокации у тебя изменится? Тогда проще будет все в одном файле небольшом поправить, а контроллер даже не трогать 👌

**Comment by EvangelinaKlyukay** [comment]
сделала, с горем пополам)
