### ISSUE TITLE
В — внимательность :]

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#8]
https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Controller/WeatherViewController.swift#L86

Посмотри внимательно имена параметров которые ты запрашиваешь :) Есть тут ошибочка* ;) 

*у тебя `lat` всегда равна `lon` ;D

**Comment by EvangelinaKlyukay** [comment]
let lon = location.coordinate.longitude
Так?
