### ISSUE TITLE
UIAlertController

### ISSUE THREAD

**Issue by h4pp** [EvangelinaKlyukay/Clima#9]
https://github.com/EvangelinaKlyukay/Clima/blob/cfd097281e4ec42260b0f5d5371a7cac8f4949d0/Clima/Controller/WeatherViewController.swift#L92

А прикрути ко всем ошибкам https://developer.apple.com/documentation/uikit/uialertcontroller — и выводи туда в `message` параметр `error.localizedDescription`
Пусть и пользователь узнает если что-то пошло не так 👌

**Comment by EvangelinaKlyukay** [comment]
Вроде сделала

**Comment by h4pp** [comment]
```swift
        let alert = UIAlertController(title: "Error", message: error.localizedDescription, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: NSLocalizedString("OK", comment: "Default action"), style: .cancel, handler: { _ in
            NSLog("The \"OK\" alert occured.")
        }))
        self.present(alert, animated: true, completion: nil)

```

Смотри какое дело: у тебя вот этот код повторяется дважды. А что если `title` надо будет изменить в обоих сразу? Например добавишь локализацию и надо будет искать все такие куски кода?
Лучше заведи отдельный метод в контроллере, который будет принимать `Error`, а все остальное будет делать сам :)

**Comment by EvangelinaKlyukay** [comment]
сделала
